### ISSUE TITLE
Instagram disappears entirely

### ISSUE THREAD

**Issue by Luftschlosser** [otsmr/inline-popup-blocker#12]
It's a bit ironic, but the entire content of https://www.instagram.com disappears completely with this plugin. It would be nice to be able to deactivate the plugin only on certain sites to help with issues like this.

**Comment by otsmr** [comment]
You can do that :). There is a Button in the Address Bar:
https://user-images.githubusercontent.com/48922451/120222849-e7590b00-c240-11eb-914f-33d383aa85de.png
